Rewrite votedFor and add leader propagation queue
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #111
Opened 2023-02-17 11:50 UTC by kjarosh

2023-02-17 14:13 UTC, Rados13 requested changes
I have two issues. First I am not sure about renaming `VotedFor` to `RaftLeader`, because `votedFor` is a term from paper. Secondly, these changes make tests pass once on three times.

2023-02-17 14:13 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftLeader.kt
> +    }
This function doesn't handle situations when you are elected as a leader. In that situation, you will block yourself from sending http requests to yourself and don't schedule sending heartbeats. Which then leads to very strange

2023-02-17 14:13 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftLeader.kt
> +    }
Why does `propagateChange` call `propagateChanges` which calls another method `propagateChange`?

2023-02-22 15:50 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        if (electedLeader == globalPeerId) {
As far as I understand, you can synchronize on L694 but when execution reaches L697 the electedLeader variable might be outdated?

2023-02-22 15:50 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftLeader.kt
> +                launch(MDCContext()) {
why do you launch another MDCContext? shouldn't we use the one we have (somehow)?

2023-02-22 15:50 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftLeader.kt
> +        logger.info("Propagating change to leader ($leaderId): $change")
I don't think its intuitive that class named `RaftLeader` logs `propagating change to leader` which means that this is not raft leader.

2023-02-22 15:50 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftLeader.kt
> +            response
I don't know if I'm right, but I'd advise not to call specific httpClient from here, which can make testing hard.

2023-02-24 19:49 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftLeader.kt
> +            response
We use specific httpClient from each module :upside_down_face:

2023-02-24 19:51 UTC, Rados13 reviewed
This PR also looks good, maybe it's even more idiomatic for OOP. But I would also run it 50 times to check if there is no race condition.

2023-02-27 14:43 UTC, closed without merging