Add peersets
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #13
Opened 2022-06-07 19:27 UTC by Davenury

2022-06-08 08:39 UTC, Rados13 requested changes

2022-06-08 08:39 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +                            httpClient.post<K>("http://$it/$urlPath") {
We could move the URL to a variable.

2022-06-08 08:49 UTC, Davenury commented on build.gradle.kts
> -tasks.register<Test>("integrationTest") {
Yeah, I know. I'll still leave them (so we know we didn't break anything during changes) but still tests for multiple peersets will cause some pain because of env variables we have to pass to the application.

2022-06-08 08:50 UTC, Davenury commented on src/main/kotlin/com/example/Application.kt
> +        result
I'll try, but I'm not as functional god as you're

2022-06-08 08:55 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +    private var transaction: Transaction = Transaction(myBallotNumber, Accept.ABORT)
Tbh I forgot about it, but I think we should reset it after any transaction. I don't know if null won't cause any problems but I'll try

2022-06-08 08:56 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        logger.info("Lock aquired: ${message.ballotNumber}")
Debug is disabled in logger (as ratis produce so many logs in debug), so I used info.

2022-06-08 08:58 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
>          semaphore.release()
I don't think so. There could be exception in applying change but I can change it to "try finally" block.

Also a question - if we'll apply change to ratis from three cohorts, it will be applied three times, right? That's something we should also check.

2022-06-08 08:59 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        otherPeers: List<List<String>>,
Like those are other peers. They are splitted in peersets but still

2022-06-08 09:00 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +    }
Yeah, some kind of optimalization thing got into me. I'll change 😂

2022-06-08 09:01 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        return responses.withIndex().all { (index, value) -> value.size > peersInTransaction[index].size / 2 }
Tbh I'd thought about generalizing those two functions.

2022-06-08 09:07 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
>          semaphore.release()
Yeah, we should check this but this shouldn't make difference as in Ratis you apply a whole new state (it works like a single source of truth), so when we apply it three times this shouldn't make any errors but we should check it for certainty

2022-06-08 09:09 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            if (!superSet(otherPeers, electResponses)) {
The first leader is using superSet, after the leader failed we use superMajority.

2022-06-08 09:10 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        return responses.withIndex().all { (index, value) -> value.size > peersInTransaction[index].size / 2 }
Good idea

2022-06-08 17:06 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
>          semaphore.release()
That's something we've agreed on asking, do I remember correctly?

2022-06-09 06:19 UTC, Rados13 approved these changes
Only small comments

2022-06-09 06:19 UTC, Rados13 commented on src/main/kotlin/com/example/Application.kt
> +                acc
Do you know that you can return simply `acc + string`?

2022-06-09 06:19 UTC, Rados13 commented on src/main/kotlin/com/example/Application.kt
> +                acc
Same as below

2022-06-09 06:19 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        } while (!superMajority(otherPeers, electResponses) && tries < maxLeaderElectionTries)
This change isn't correct, as getting `elect-you` from superMajority is enough only when the cohort is trying to become a leader after the failure of the previous leader, if this is first time leader he has to get `elect-you` from superSet.

2022-06-09 06:19 UTC, Rados13 commented on src/main/kotlin/com/example/raft/Constants.kt
> +    fun getPeers() = PEERS
Man will come out from Java, but Java will never come out from the man.

2022-06-09 07:16 UTC, Davenury commented on src/main/kotlin/com/example/raft/Constants.kt
> +    fun getPeers() = PEERS
XDDDDDD
But it has more meaning than just Java. See that I needed to change it to var. So I made the variables private and set getters so we (or someone else) don't accidentally override those variables with some garbage.

2022-06-09 07:18 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        } while (!superMajority(otherPeers, electResponses) && tries < maxLeaderElectionTries)
I think this is correct (though we need to talk about this today). We're waiting first for supermajority, then we're checking if this was fail (e.g. someone got decision or someone got accept Val to commit). Then if that's not the case, we're checking if we've actually got superSet. Now there's to-do, but in the other PR I filled that todo

2022-06-09 07:19 UTC, Davenury commented on src/main/kotlin/com/example/Application.kt
> +                acc
I had that once but then it didn't compile, so I'm gonna check it once more

2022-06-09 07:25 UTC, Rados13 commented on src/main/kotlin/com/example/raft/Constants.kt
> +    fun getPeers() = PEERS
If you want do this Kotlin way:
https://stackoverflow.com/questions/33428957/kotlin-public-get-private-set-var
https://kotlinlang.org/docs/properties.html#backing-fields
There were reasons why Scala and then Kotlin add these features (mostly to not generate boilerplate like the code above).

2022-06-09 07:37 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        } while (!superMajority(otherPeers, electResponses) && tries < maxLeaderElectionTries)
As this PR doesn't handle recovery of transactions after leader failure so the same way should work protocol. So if protocol state that the first leader should get the `elect-you` message from superSet so it should get the same in our code, instead of relying on hacks that we run the application locally so always cohort responds.

2022-06-09 17:22 UTC, Davenury commented on src/main/kotlin/com/example/Application.kt
> +                acc
![image](https://user-images.githubusercontent.com/57959794/172907139-64b67c5d-1edd-42e1-b6fa-f68567679dc9.png)

2022-06-09 18:04 UTC, Rados13 approved these changes

2022-06-09 18:13 UTC, merged