first try
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #130
Opened 2023-03-02 15:35 UTC by Davenury

2023-03-02 23:45 UTC, kjarosh requested changes
This PR needs https://github.com/Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC/pull/128

2023-03-06 10:04 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocolClient.kt
> +                logger.info("Sending regest ")
A typo

2023-03-06 10:04 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +            logger.info("Leader send message to $peerAddress $newProposedChanges")
Not grammatical

2023-03-06 10:05 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/routing/consensusProtocolRouting.kt
> +                    runBlocking {
I believe `runBlocking` is not required here

2023-03-06 10:07 UTC, kjarosh submitted a review, later dismissed

2023-03-11 13:40 UTC, Rados13 approved these changes

2023-03-13 10:52 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        isRegular: Boolean = false, sendInstant: Boolean = false,
```suggestion
        isRegular: Boolean = false,
        sendInstantly: Boolean = false,
```

2023-03-13 10:52 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/utils.kt
> +        connectTimeoutMillis = 100
100ms is way too low

2023-03-13 10:57 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +            expectThat(e.response.status).isEqualTo(HttpStatusCode.NotFound)
It does not make much sense

2023-03-13 13:30 UTC, kjarosh approved these changes

2023-03-13 13:36 UTC, merged