Leader fail
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #14
Opened 2022-06-08 20:14 UTC by Davenury

2022-06-09 07:14 UTC, Rados13 requested changes

2022-06-09 07:14 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +    }
As each phase has got the same steps but it has got a little different state, this looks similar to a state machine and I think that refactoring it to a state machine can improve readability a lot.

2022-06-09 15:44 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        }
Continue with protocol

2022-06-09 15:54 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +    }
For today no, for the future - of course 😄

2022-06-22 16:49 UTC, Rados13 requested changes
I think further tests should be focused on failures inside shards e.g: we have two shards each with 3 or 5 nodes and what happens when all or majority of nodes from one shard fail before the leader sends ft-agree/apply etc. Because I have a feeling that there are some edge cases regarding shards, which we don't handle properly.

2022-06-22 16:49 UTC, Rados13 commented on src/main/kotlin/com/example/raft/HistoryStateMachine.kt
> +                state.add(ChangeWithAcceptNum(change, acceptNum))
Create function `ChangeWithAcceptNum.fromJson`.

2022-06-22 16:49 UTC, Rados13 commented on src/main/resources/single_peerset_application.conf
> +    leaderFailTimeoutInSecs = 3
It's quite a big change of timeout 🤣

2022-06-22 16:49 UTC, Rados13 commented on src/test/kotlin/com/example/api/IntegrationTest.kt
> +        deleteRaftHistories()
Could we move this line to `@BeforeEach`?

2022-06-22 16:49 UTC, Rados13 commented on src/test/kotlin/com/example/api/IntegrationTest.kt
> +                val url = "http://localhost:8082/ft-agree"
Could we move these pairs localhost and port to variables like `peer1` and `peer2`?

2022-06-22 16:49 UTC, Rados13 commented on src/test/kotlin/com/example/api/IntegrationTest.kt
> +        }
What do you think about adding a comment that there we check if a transaction was processed after leader failure?

2022-06-23 20:55 UTC, Davenury commented on src/main/kotlin/com/example/api/Routing.kt
> +                val result = historyManagement.change(change.toChange(), 1)
The whole purpose of this endpoint was to test Ratis. IMO I would get rid of it.

2022-07-02 20:19 UTC, Rados13 requested changes

2022-07-02 20:19 UTC, Rados13 commented on src/main/kotlin/com/example/domain/ProtocolClient.kt
> +                            acc = aggregateErrors(acc, value)
Create a function for that or add some description about what happened here.

2022-07-02 20:19 UTC, Rados13 commented on src/main/kotlin/com/example/domain/ProtocolClient.kt
> +                        }
You probably can move the null outside the if-else.

2022-07-02 20:19 UTC, Rados13 commented on src/main/kotlin/com/example/infrastructure/ProtocolTimerImpl.kt
> +            delay((delay + randomGenerator.nextLong() % backoffBound) * 1000)
I assume that 1000 is, because of moving from seconds to milliseconds. Make it variable with a good name.

2022-07-02 20:19 UTC, Rados13 commented on src/main/kotlin/com/example/utils.kt
> +        configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true)
What does this configuration change?

2022-07-02 20:19 UTC, Rados13 commented on src/test/kotlin/com/example/api/SinglePeersetIntegrationTest.kt
> +        println("here")
Do we need all of these `println`?

2022-07-02 22:06 UTC, Davenury commented on src/main/kotlin/com/example/api/Routing.kt
> -            }
It's an endpoint which gives you access directly to Ratis, without our protocol. Since it's not needed, I removed it

2022-07-02 22:07 UTC, Davenury commented on src/main/kotlin/com/example/config.kt
> +        .also { println(it) }
Considering it logs out whole config, it's not something I would leave for production 😂 tbh I must have forgotten about this one

2022-07-02 22:08 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            electResponses = responses
Just for the deconstruction but I'll look how to use it better.

2022-07-02 22:09 UTC, Davenury commented on src/main/kotlin/com/example/domain/ProtocolClient.kt
> +                            acc = aggregateErrors(acc, value)
> When I wrote this code, only I and God knew what was happening here. Now only God knows.

2022-07-03 12:17 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            throw NotElectingYou(myBallotNumber, message.ballotNumber)
I'll change it to `NotValidLeader` - should be better

2022-07-03 12:19 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            electResponses = responses
https://stackoverflow.com/a/39273672 -> I think that's the way you do it in Kotlin,

2022-07-03 12:26 UTC, Davenury commented on src/main/kotlin/com/example/utils.kt
> +        configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true)
TBH, I don't remember. I guess that I had some problem with object mapping and this option either helped or not and I forgot to delete it. Anyway, it doesn't do any harm for now, so I'd leave it be.

2022-07-03 12:26 UTC, Davenury commented on src/test/kotlin/com/example/api/SinglePeersetIntegrationTest.kt
> +        println("here")
yeah, without them tests aren't passing 😄

2022-07-03 17:49 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            throw NotElectingYou(myBallotNumber, message.ballotNumber)
I am unsure if making the same exception for situations when you are not elected as leader and you should be elected as leader but, before you send ft-agree the peer has incremented ballot number is a good idea.

2022-07-03 17:52 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            electResponses = responses
Ok, but my question was more about that `electResponse` isn't changed in this function, so we could name it this way in deconstruction and don't add an additional variable.

2022-07-03 17:54 UTC, Rados13 commented on src/test/kotlin/com/example/api/SinglePeersetIntegrationTest.kt
> +        println("here")
Could we use the here logger?

2022-07-03 17:57 UTC, Rados13 commented on src/main/kotlin/com/example/domain/ProtocolClient.kt
> +                        // get any aggregation from all responses from "Not electing you" response, so we can get
We don't have now NotElectYou exception but I would add it again 😄

2022-07-03 17:58 UTC, Davenury commented on src/test/kotlin/com/example/api/SinglePeersetIntegrationTest.kt
> +        println("here")
it was just a joke, I believe that I got rid of them

2022-07-03 18:00 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            electResponses = responses
we can't. When I tried to do that, variable defined above while is other variable and then it's "not initialized" after while.

2022-07-03 18:10 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            electResponses = responses
Ok so I would add 
```kotlin
if(superFunction(electResponses) return electResponses
```
And after a while stay only with the body of if.

2022-07-04 13:05 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            throw NotElectingYou(myBallotNumber, message.ballotNumber)
It's still the same thing. In either case you're not a valid leader.

2022-07-04 13:05 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            electResponses = responses
I don't get it

2022-07-04 19:39 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            throw NotElectingYou(myBallotNumber, message.ballotNumber)
`Not a valid leader` in ft-agree phase, `Not Electing You` in elect phase

2022-07-04 19:56 UTC, Rados13 approved these changes

2022-07-04 20:16 UTC, merged