The first version of consensus implementation
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #24
Opened 2022-07-19 19:57 UTC by Rados13

At the moment, consensus tests sometimes pass.

2022-07-21 14:00 UTC, Davenury commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +            timer.cancelCounting()
What is this canceling?

2022-07-21 14:02 UTC, Davenury commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        proposeChange(change.change, change.acceptNum)
Wouldn't we like to return to the user information about if his change was accepted or not?

2022-07-21 16:14 UTC, Davenury commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        if (amILeader() || iteration <= leaderIteration) {
Shouldn't here be also checked if leader already exists?

2022-07-21 19:29 UTC, Rados13 commented on src/main/kotlin/com/example/Application.kt
> +
It depends on the config in the config for containers it will be and it will be `peer{offset}:8080` in others it will be  `127.0.0.1:{8080 + offset}`.

2022-07-21 19:33 UTC, Rados13 commented on src/main/kotlin/com/example/common/ProtocolTimer.kt
> +    }
I was thinking about shorting backoff for a heartbeat, but in the end, I didn't use this method so I will delete it.

2022-07-21 19:36 UTC, Rados13 commented on src/main/kotlin/com/example/common/InMemoryHistoryManagement.kt
> +        runBlocking {
I was thinking it will be easier to change it in one place and not work a the moment by changing all places where we use it but now I can switch it to suspend.

2022-07-21 19:42 UTC, Rados13 commented on src/main/kotlin/com/example/consensus/raft/domain/Ledger.kt
> +data class LedgerItemDto(val id: Int, val change: ChangeWithAcceptNumDto) {
I think that two changes with the same id can be proposed, but only one should be accepted.

2022-07-21 19:51 UTC, Rados13 commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +            timer.setDelay(heartbeatDue.toMillis().toInt())
Yeah, this setting delay is duplication and I will remove it. As for changing the delay of the timer, we changed it to be sure that the delay in waiting for a new leader is correct because in different states of consensus timer delay has different values.

2022-07-21 19:53 UTC, Rados13 commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        if (!checkHalfOfPeerSet(responses.size)) {
As you can see we few lines upper we are filtering responses for only this that have `voteGranted` to true, so I will change the name of a variable to `positiveResponses`.

2022-07-21 19:57 UTC, Rados13 commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        timer.setDelay(halfDelay)
I was thinking about it too, but I decided that bugs that can be a consequence of running two timers at the same time will be a lot harder to debug than this from handling only one timer.

2022-07-21 19:58 UTC, Rados13 commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +            return ConsensusElectedYou(this.peerId, false)
What should I correct?

2022-07-21 20:04 UTC, Rados13 commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        restartLeaderTimeout()
So you would like me to add some flag to the timer and set it outside of the timer and this flag would decide if action after time is running or not?

2022-07-21 20:07 UTC, Rados13 commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +            timer.cancelCounting()
This is canceling the scheduled heartbeat, because we will send this heartbeat earlier than it was scheduled.

2022-07-21 20:14 UTC, Rados13 commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        proposeChange(change.change, change.acceptNum)
It would be nice to have this, but pretty much it can take much longer than request timeout eg. we have only 3 peers out of 5 and one peer is chosen as a leader. Then one of the non-leader peers failed so we have only 2 peers including the leader. In this situation, a client can propose change, and this change will not be accepted or rejected until another peer comes.

2022-07-21 20:16 UTC, Rados13 commented on src/main/kotlin/com/example/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        if (amILeader() || iteration <= leaderIteration) {
No, because if any of the nodes request to become a leader now it should be allowed. At least that's how the raft demo is working 😄.

2022-08-10 22:35 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +    consensusAdditionalActions: Map<ConsensusTestAddon, AdditionalActionConsensus> = emptyMap(),
I would merge `signalListeners` and `consensusAdditionalActions` — just prefix signals with `Consensus`

2022-08-10 22:35 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/common/Change.kt
>                  throw UnknownOperationException(it)
What's the point of handling exceptions in this way?
1. `ex` is ignored, but should be passed as a root cause
2. The error is both logged and propagated. Handling exceptions in such way will just cause duplicate exceptions to be logged over and over.

2022-08-17 15:07 UTC, Davenury requested changes

2022-08-17 15:07 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        }
I'd make three funcions out of this, becasue it's too huge for one function 😄 Then you could also use `when`

2022-08-17 15:07 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +                "$peerId - $e"
Log exception

2022-08-17 15:07 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        private val leaderTimeout = Duration.ofMillis(500)
I think that this should be passed as class constructor agruments and moved out to config.

2022-08-17 15:07 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +//data class ConsensusPeer(
If it's not used, delete this comment.

2022-08-17 15:07 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/utils.kt
> +
why XDDD

2022-08-17 15:07 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +            .let { it ->
You don't have to name the lambda parameter `it` - it will have this name by default

2022-08-17 15:07 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/consensus/ConsensusSpec.kt
> +            consensusProtocol.javaClass.getDeclaredField("consensusPeers").let { field ->
I'm quite sure that I've added `setPeers` function, please, don't use this unless it's really really necessary

2022-08-17 17:28 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/SignalListener.kt
> +    ConsensusAfterProposingChange
I don't have an opinion about that. @kjarosh suggested merging it, so please make some consensus about it 😄.

2022-08-17 17:29 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/common/Change.kt
> -                throw UnknownOperationException(it)
Same as above.

2022-08-17 17:43 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/common/commonRouting.kt
> +            val properties = call.receive<Map<String, Any>>()
In the line below, we are casting the field of this map, not the whole map.

2022-08-17 18:00 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/domain/Ledger.kt
> +    fun getLastAcceptedItemId() = acceptedItems.lastOrNull()?.id ?: -1
We start iterating ids from 0, so we return -1 when there aren't any accepted items, but as we don't use this function I can remove it.

2022-08-17 18:16 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/consensus/ConsensusSpec.kt
> +            consensusProtocol.javaClass.getDeclaredField("consensusPeers").let { field ->
But it looks so good 😄

2022-08-20 09:06 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/SignalListener.kt
> +    ConsensusAfterProposingChange
Like I said, maybe it's just me. So let it be like this

2022-08-20 09:06 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/common/Change.kt
> -                throw UnknownOperationException(it)
@kjarosh

2022-08-20 09:09 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +    private lateinit var consensusProtocol: RaftConsensusProtocolImpl
Yes it will

2022-08-20 13:03 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +        consensusProtocol.setLeaderAddress(address)
At start we're assuming we're leader?

2022-08-20 13:04 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/domain/RaftProtocolClient.kt
> +            body = message!!
message isn't nullable here, so why this check?

2022-08-20 13:05 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/common/HistoryManagement.kt
> +                    ConsensusResultUnknown -> HistoryChangeResult.HistoryChangeSuccess
Unknown == Success?

2022-08-20 13:06 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +    private val leaderTimeout: Duration = Duration.ofMillis(500)
Better, but I still think it should be in config files.

2022-08-20 13:08 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        println("Response from leader: $response")
Isn't there logger (maybe it's in Kamil's PR, therefore the question)

2022-08-20 13:08 UTC, Davenury reviewed
As in comments

2022-08-20 13:48 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/domain/RaftProtocolClient.kt
> +            body = message!!
Without it there is `Type mismatch`

2022-08-20 13:52 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/common/HistoryManagement.kt
> +                    ConsensusResultUnknown -> HistoryChangeResult.HistoryChangeSuccess
Yeah, this is, but I don't know how to handle this better, so for now, I made it success 😅

2022-08-20 13:53 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        println("Response from leader: $response")
This is some left from debugging.

2022-08-20 13:53 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +        consensusProtocol.setLeaderAddress(address)
Yeah it is bad assumption, I don't know why I add this 😅

2022-08-27 13:05 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/domain/RaftProtocolClient.kt
> +            body = message!!
Ok, weird, but since Kotlin needs it...

2022-08-27 13:05 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/domain/messages.kt
> +data class ConsensusProposeChange(val change: ChangeWithAcceptNumDto)
I won't require you to change it, but what's the purpose of this class? Why not use `ChangeWithAcceptNumDto` as `ConsensusProposeChange` (I'd also add dto, if that's what you're handling here - I think it's not good that possibly domain class contains dto class).

2022-08-27 13:05 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +package com.example.consensus.raft.infrastructure
package name

2022-08-27 13:05 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        println("$peerId - Peers: $otherPeers \n old: $consensusPeers")
You've got logger here

2022-08-27 13:05 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/consensus/ConsensusSpec.kt
> +        println("Stop 2 application")
println?

2022-08-27 14:52 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +        consensusProtocol.setLeaderAddress(address)
Yeah in the end this was a bad function name 😅.

2022-08-28 10:59 UTC, Davenury requested changes

2022-08-28 10:59 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +        val address = "localhost:${getBoundPort()}"
Imo it can't stay like this. Localhost can only be used in local and test env, docker compose and k8s won't be able to resolve this in the way we want to. Change ilocalhost to `ApplicationMode#host` and it SHOULD do the trick (but still use docker compose to test it).

2022-08-29 13:52 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/ApplicationMode.kt
> +import java.time.Duration
unused import?

2022-08-29 13:52 UTC, Davenury commented on src/main/resources/application-compose.conf
> +    leaderTimeout = PT0.5S
I think it would be better to use 500 ms, but I'm not really familiar with that format, so let it be I guess.

2022-08-29 13:52 UTC, Davenury commented on src/main/resources/consensus_application.conf
> +            storage {
Do we need this storage in here, since we don't use ratis anymore?

2022-08-29 13:52 UTC, Davenury commented on src/main/resources/consensus_application.conf
> +    clusterGroupIds = [
Here also - we don't use Ratis, so why do we keep it?

2022-08-29 13:52 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/consensus/ConsensusSpec.kt
> +        delay(leaderElectionDelay)
tbh I don't think it's a good idea to come back to delays, since we already had so much trouble in cleaning them up. But I think this could be adressed in next PR.

2022-08-29 13:52 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/consensus/ConsensusSpec.kt
> +            (1..5).map { createApplication(arrayOf(it.toString(), "1"), mode = TestApplicationMode(it, 1)) }
We've already created util for creating applicatios in easier way, using ephemeric ports at the top of that.

2022-08-29 16:14 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/consensus/ConsensusSpec.kt
> +        delay(leaderElectionDelay)
Yup that's right.

2022-08-29 16:16 UTC, Davenury approved these changes

2022-08-29 17:14 UTC, Davenury approved these changes

2022-08-29 17:14 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +    fun getRunningApps(): List<Application> = apps
I don't get why do you need this. Isn't `peers` or `getRunningPeers` enough? You're killing encapsulation here but I guess it's just me doing my "pitu-pitu", so it could stay, if you really need this.

2022-08-29 17:47 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +    fun getRunningApps(): List<Application> = apps
Nope, it is not enough, because in tests I am checking if a peer chose a leader, and you said that the endpoint for checking a leader is useless so I removed it and now I am getting a leader address from a peer with the use of reflection.

2022-08-29 17:55 UTC, merged