Ephemeric ports
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #28
Opened 2022-07-30 18:21 UTC by Davenury

2022-07-30 20:11 UTC, Davenury commented
During review I highly adivce to skip first commit - it's just changing package from `com.example` to `github.davenury.ucac`

2022-07-31 11:14 UTC, kjarosh commented on src/main/kotlin/github/davenury/ucac/ApplicationMode.kt
> +        } catch (e: java.lang.IndexOutOfBoundsException) {
`e` is lost here

2022-07-31 11:14 UTC, kjarosh commented on src/main/kotlin/github/davenury/ucac/ApplicationMode.kt
> +                "Peers addresses doesn't have enough elements in list - peers addresses length: ${config.peers.peersAddresses.size}, index: ${peersetId - 1}"
This should probably be an exception message

2022-07-31 11:16 UTC, kjarosh commented
We could aggregate application objects into one in tests which handles lifecycle and peer discovery

2022-08-01 17:55 UTC, Rados13 requested changes

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +    actions: Map<Int, Map<TestAddon, suspend (ProtocolTestInformation) -> Unit>> = emptyMap(),
As we have typealias use it ( `AdditionalAction`)

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +                println(absoluteIndex)
If it is useful I would change it to use logger if not remove it.

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +        )
Shouldn't we check if these ports are not used already?

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +        }
What do you think of using for loops or sequence/generators?

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +                        TestApplicationMode(peerId + 1, peersetId + 1)
Could we move this `peerId+1` and `peersetId+1` to variables?

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +                .map { it.map { "localhost:${it.getBoundPort()}" } }.toMutableList().map { it.toMutableList() }
This map is too complex IMO. Could you move it to function?

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +            "raft.server.addresses" to ratisPorts.chunked(3).map { it.map { "localhost:${it + 11124}" } }
- What do you think about moving part after `to` to some function?
- 11124 looks really like magic number

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +            createApplication(arrayOf("3", "2"), emptyMap(), mode = TestApplicationMode(3, 2), configOverrides = configOverrides),
What do you think about changing it to 
```kotlin
(1..3).zip(1..3).map{
   createApplication(
     arrayOf(it.first.toString(),it.second.toString()),
     emptyMap(), 
     mode=TestApplicationMode(it.first,it.second),
     configOverrides = configOverrides
   )
}
```

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +            val filteredPeers = peers.map { peerset -> peerset.filter { it != "localhost:${application.getBoundPort()}" } }
Could you add a function like `removeYourselfFromAllPeers`.

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
>          // val app6 = GlobalScope.launch(Dispatchers.IO) { startApplication(arrayOf("3", "2"), emptyMap()) }
Could you move it to be together with other apps and add comments that these not started applications are represented in `peers` list as these addresses `localhost:8083` etc.

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +                    List(5) { "localhost:${Random.nextInt(10001, 20000) + 11134}" })
Shouldn't we check if these ports aren't already used?

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +                    .toList()
In the previous test, there was a similar fragment of code, could we move these two fragments to some function and parameterized it properly?

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +            }
As above create a helper function.

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +                List(5) { "localhost:${Random.nextInt(10001, 20000) + 11134}" })
Create a helper function for generating raft server addresses.

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +        }
Same as above mentioned.

2022-08-01 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +            val leaderAction: suspend (ProtocolTestInformation) -> Unit = {
We have type alias for that.

2022-08-01 18:00 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/ApplicationMode.kt
> +            }
I remember that we tried this in the beginning, but sure, I can check

2022-08-01 18:01 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/EventListener.kt
>  }
yes, but it's in different PR, so for the moment I've decided not to introduce another change

2022-08-01 18:02 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +                println(absoluteIndex)
It's not I forgot to delete it in one commit but I think it's deleted now

2022-08-01 18:05 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +        }
Yeah, they are pretty useful in specific cases but personally I like list comprehensions in Python more. Thank you for comming to my TedTalk but please, consider asking such things in DM, not in review 😄 

JK, I thought that repeat was "more kotlin" way to do this, as I didn't find anything "functional" to repeat that list but I can consider something different.

2022-08-01 18:06 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +                        TestApplicationMode(peerId + 1, peersetId + 1)
yes we could

2022-08-01 18:07 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +            "raft.server.addresses" to ratisPorts.chunked(3).map { it.map { "localhost:${it + 11124}" } }
1. I don't think that's necessary (at least for now) as this will be encapsulated in another class.
2. Because it is. It was port from conifg and in breif moment of not being able to think clearly I thought it was somehow important.

2022-08-01 18:08 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +            createApplication(arrayOf("3", "2"), emptyMap(), mode = TestApplicationMode(3, 2), configOverrides = configOverrides),
It will be moved to another class and there it will be made better, but for now I'd leave it here, since we're only caring for "working" part now (as it was mentioned at the meeting)

2022-08-01 18:09 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +            val filteredPeers = peers.map { peerset -> peerset.filter { it != "localhost:${application.getBoundPort()}" } }
I could, but I won't. JK, I will in class mentioned before.

2022-08-01 18:10 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +                    List(5) { "localhost:${Random.nextInt(10001, 20000) + 11134}" })
Like before, I don't think it's necesarry - we randomize for specific reason and I don't know if there's a "non painful" way to check it in java.

2022-08-01 18:10 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +                    .toList()
It will be moved to another class.

2022-08-01 18:17 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +        }
The biggest problem I see with repeat is that it didn't return value, that is why I mentioned Kotlin `sequence` which can do this.

2022-08-01 18:21 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/MultiplePeersetSpec.kt
> +            "raft.server.addresses" to ratisPorts.chunked(3).map { it.map { "localhost:${it + 11124}" } }
I want mostly it to function because we use the same line in two places in this test, and also it isn't easy to understand what this line does.

2022-08-01 18:24 UTC, merged

2022-08-02 16:12 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/ApplicationMode.kt
> +            }
![image](https://user-images.githubusercontent.com/57959794/182422423-2e22de7f-bd86-47ad-9d05-83da8d01c03c.png)