review fixes
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #30
Opened 2022-08-02 17:42 UTC by Davenury

2022-08-04 21:00 UTC, kjarosh commented
I believe there's an error in commit history: probably a wrong rebase?

2022-08-06 12:47 UTC, Rados13 requested changes

2022-08-06 12:47 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +                    TestApplicationMode(peerId + 1, peersetId + 1)
As I understand add one to `peerId` and `peersetId` because we start iterating from 1, why do we do that to ourselves? I would change that we start iterating like all programmers from 0 😄.

2022-08-06 12:47 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +        apps.flatten().forEachIndexed { index, app -> if (index + 1 !in appsToExclude) app.startNonblocking() }
What do you think about this change?
```suggestion
        apps
        .flatten()
        .filterIndexed { index, _app -> !appsToExclude.contains(index+1) }
        .forEach{ it.startNonblocking() }

```

2022-08-06 12:47 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +                .mapIndexed {index, it -> Pair(it, if (index + 1 in appsToExclude) "localhost:0" else "localhost:${it.getBoundPort()}") }
What do you think about this change?
```suggestion
                .mapIndexed {index, it -> 
                val address = if (index + 1 in appsToExclude) "localhost:0" else "localhost:${it.getBoundPort()}"
                Pair(it, address) 
                }

```

2022-08-06 12:47 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +            }
What do you think about using `filterIndexed` first and then `forEach`?

2022-08-06 12:47 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +                    peers.map { it.filterNot { it == peer } }
I think that removing peer peerset or peersets is very common, so we could make it a function.

2022-08-06 12:47 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetIntegrationTest.kt
>                  println("Other peer sent response to ft-agree: $response")
Is this needed?

2022-08-06 12:47 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetIntegrationTest.kt
> +            configOverrides = (1..5).zip(List(5) { configOverrides }).toMap()
What do you think about moving this to a variable like `peerIdToNewConfig`?

2022-08-10 18:01 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/consensus/ConsensusSpec.kt
> +    private val peer2 = "http://localhost:8082"
It's consensus, I didn't deal with it

2022-08-10 18:21 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/consensus/ConsensusSpec.kt
> +    private val peer2 = "http://localhost:8082"
Ok so it is a result of wrong rebase

2022-08-10 18:27 UTC, Rados13 requested changes
Also, tests fail and there are still some conflicts.

2022-08-10 18:27 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +                    peers.map { it.filterNot { it == peer } }
What about this?

2022-08-10 18:27 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetIntegrationTest.kt
> +            configOverrides = (1..5).zip(List(5) { configOverrides }).toMap()
Ok

2022-08-10 18:28 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +                    peers.map { it.filterNot { it == peer } }
yeah, I don't think so. For now (as far as I could see) we've used this mechanizm twice, every time it was in different context and with slight different approach, as some other outcome was needed - I don't think we should make a function for that for now.

2022-08-15 17:55 UTC, Rados13 approved these changes

2022-08-15 17:55 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetIntegrationTest.kt
> +                fail("Change passed")
Why did you change the comment?

2022-08-16 15:45 UTC, merged

2022-08-16 15:46 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetIntegrationTest.kt
> +                fail("Change passed")
It works better, as "Didn't work" is double negation and here change passes, even though it shouldn't

2022-08-16 15:48 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetIntegrationTest.kt
> +                fail("Change passed")
Yeah but now we have fail with the name `Change passed`.