Metrics
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #34
Opened 2022-08-17 18:38 UTC by Davenury

This PR will also consist everything k8s related (yamls, scripts, READMEs etc.)

2022-10-11 16:19 UTC, Davenury commented
As you'll review this PR, you can go ahead and skip all golang files (unless you want to but if you've never written anything in it, it may be hard for you to review it).

2022-10-11 17:30 UTC, Rados13 requested changes

2022-10-11 17:30 UTC, Rados13 commented on cmd/commands/cleanup.go
> +}
This fragment from `DeleteCollection` is the same as in `deleteDeployments`, could we move it to the util function?

2022-10-11 17:30 UTC, Rados13 commented on cmd/commands/deploy.go
> +	// "k8s.io/client-go/plugin/pkg/client/auth"
Shouldn't we remove these commented fragments?

2022-10-11 17:30 UTC, Rados13 commented on cmd/commands/deploy.go
> +				"prometheus.io/path":   "/_meta/metrics",
Shouldn't that be more parameterized?

2022-10-11 17:30 UTC, Rados13 commented on cmd/commands/deploy.go
> +		},
Couldn't we generate these addresses before and here only assign values under keys?

2022-10-11 17:30 UTC, Rados13 commented on k8s-stuff/one-pod/README.md
> +
Could you create a bash script for checking if you have locally installed all needed tools? It could also create `namespace tryout` if it doesn't exist already.

2022-10-11 17:30 UTC, Rados13 commented on k8s-stuff/one-pod/README.md
> +```
Could you add to mention above script all helm installation?

2022-10-11 17:30 UTC, Rados13 commented on k8s-stuff/one-pod/README.md
> +Now you have prometheus datasource and can begin fun with grafana.
Couldn't we configure it from the terminal e.g by sending HTTP requests via curl or something like this?

2022-10-11 17:30 UTC, Rados13 commented on k8s-stuff/one-pod/README.md
> +```
Could we create a bash script, which would setup everything up?

2022-10-11 17:30 UTC, Rados13 commented on k8s-stuff/one-pod/configmap.yaml
> +  GPAC_PEERS_ADDRESSES: "[]" # TODO []
These TODOs are still valid?

2022-10-11 17:30 UTC, Rados13 commented on k8s-stuff/one-pod/deployment.yaml
> +  name: "peer1-from-peerset1-deployment" # TODO sth like peer_n_from_peerset_k_deployment
Will you solve this TODO in this PR?

2022-10-11 17:30 UTC, Rados13 commented on metrics/local/setup.sh
> +# right now prometheus cannot connect to applications but can connect to grafana XD
Will it be solved in this PR?

2022-10-11 17:30 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/common/commonRouting.kt
> +        }
Why do we need this endpoint?

2022-10-11 17:32 UTC, Davenury commented on Dockerfile
> +RUN gradle build --info --no-daemon -x test
It excludes task `test` - building of the docker image is much quicker

2022-10-11 17:34 UTC, Davenury commented on cmd/commands/cleanup.go
> +var cleanupNamespace string
actually it's not global - it's contained in this package. Also, while working with cobra, they often use this kind of pattern [like here](https://www.thorsten-hans.com/lets-build-a-cli-in-go-with-cobra/) (section "Adding flags to commands with Cobra)

2022-10-11 17:35 UTC, Davenury commented on cmd/commands/cleanup.go
> +	})
tbh I don't know XD examples of this client also use that context, so I figured that it doesn't hurt that much. If it does, I can do some research about this but I don't know if we have enough time.

2022-10-11 17:37 UTC, Davenury commented on cmd/commands/cleanup.go
> +}
Yeah, no. Remember that golang is simple language and here we're using different objects, so even if it seems simillar, it won't be that easy to exclude it somewhere else.

2022-10-11 17:38 UTC, Davenury commented on cmd/commands/deploy.go
> +				"prometheus.io/path":   "/_meta/metrics",
why? we always expose port 8080 in k8s apps and we always have "/_meta/metrics" endpoint - imo it's not something that we should parametrized here but to keep track of it in the code

2022-10-11 17:38 UTC, Davenury commented on cmd/commands/deploy.go
> +		},
Probably. I remember I even had that idea but I forgot about it.

2022-10-11 17:39 UTC, Davenury commented on k8s-stuff/one-pod/README.md
> +
I can try. Also notice, that this is only for one-pod stuff so it's basically testing before testing.

2022-10-11 17:41 UTC, Davenury commented on k8s-stuff/one-pod/README.md
> +Now you have prometheus datasource and can begin fun with grafana.
Yes, but it's kind of pain to do so. Anyway I guess it will be necessary, so I can think of creating custom grafana image for it, but not in this PR, as it's big as it is and I don't want to rebase it after Kamil's changes.

2022-10-11 17:42 UTC, Davenury commented on k8s-stuff/one-pod/README.md
> +```
This is only "manual" testing. I think I should have deleted it but I decided that you maybe would want to see, why I used such maps in golang code. I can do bash script for setuping tools but then you have the command (I think that I could also add manual for it later on).

2022-10-11 17:43 UTC, Davenury commented on k8s-stuff/one-pod/configmap.yaml
> +  GPAC_PEERS_ADDRESSES: "[]" # TODO []
This all configmap is invalid now - we don't use it in code it was just an example I was working on before to know what to do in command - now I'm sure to either include comments or delete it.

2022-10-11 17:43 UTC, Davenury commented on k8s-stuff/one-pod/deployment.yaml
> +  name: "peer1-from-peerset1-deployment" # TODO sth like peer_n_from_peerset_k_deployment
as above

2022-10-11 17:44 UTC, Davenury commented on metrics/local/setup.sh
> +# right now prometheus cannot connect to applications but can connect to grafana XD
TBH it's just for local development that I don't think we need prometheus and grafana for.

2022-10-11 17:44 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/common/commonRouting.kt
> +        }
It's testing for metrics, I can delete it

2022-10-11 18:06 UTC, Davenury commented
The bash script and command manual will come in with next PR, as I don't want to interfere with your changes (and both script and manual will be conflict-free)

2022-10-12 19:41 UTC, Rados13 commented on k8s-stuff/one-pod/README.md
> +Now you have prometheus datasource and can begin fun with grafana.
Too late, so you can add it here :smiley:

2022-10-12 19:47 UTC, Rados13 reviewed
Almost there, a few questions left.

2022-10-12 19:47 UTC, Rados13 commented on docker-compose.yml
> -      - grafana_data:/var/lib/grafana
Why do we remove grafana and prometheus from `docker-compose`?

2022-10-12 19:47 UTC, Rados13 commented on metrics/compose/prometheus.yml
> -      - targets: ["peer1:8080", "peer2:8080", "peer3:8080", "peer4:8080", "peer5:8080", "peer6:8080"]
Won't we use prometheus anymore?

2022-10-12 19:50 UTC, Davenury commented on docker-compose.yml
> -      - grafana_data:/var/lib/grafana
I don't think we need it (tbh I don't know why we ever used docker-compose, since we could use k8s all along). Docker compose was for local development and, since I have never made grafana and prometheus to work there and we don't need them in local development, I decided to delete it.

2022-10-12 19:50 UTC, Davenury commented on metrics/compose/prometheus.yml
> -      - targets: ["peer1:8080", "peer2:8080", "peer3:8080", "peer4:8080", "peer5:8080", "peer6:8080"]
Not in compose

2022-10-12 19:54 UTC, Davenury commented on k8s-stuff/one-pod/README.md
> +Now you have prometheus datasource and can begin fun with grafana.
Nope, I can't XDD
Tbh I don't want to do it here because of changes that are about to come - I don't want to rebase it anymore, since all my changes are required to make this work on k8s

2022-10-12 19:58 UTC, Rados13 reviewed
Ok so now only one review from @kjarosh left.

2022-10-12 19:59 UTC, Rados13 approved these changes

2022-10-13 03:57 UTC, merged