Clean up config
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #43
Opened 2022-10-19 20:38 UTC by kjarosh

2022-10-19 21:41 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/ApplicationMode.kt
> +    log.info("Using application mode $applicationModeString")
Do we need this log on the info level?

2022-10-19 21:41 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/config.kt
> +    val peersetId: Int = -1,
Are we sure about this `-1`/`""`. Wouldn't it be better to use Optional, as Kotlin has great support for it?

2022-10-19 21:41 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +    private val allPeers: List<String>,
Are you sure about this field? After calling `setOtherPeers` this field can become totally outdated.

2022-10-19 21:41 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/consensus/ratis/Constants.kt
>  ) {
Are you sure about this naming? Because for me it's a bit strange that the class `RatisConfiguration` is use in the constructor variable of type `RatisConfig`.

2022-10-20 16:44 UTC, Davenury requested changes
I would love to believe that but I need to ask - did you actually run application in all modes (local, compose and k8s) and checked if your changes are working (2 peersets, 3 peers in each, 2 changes sent). I know tests are tests but we needed to have multiple changes because of tests (we're setting peers in tests e.g.).

2022-10-20 16:44 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +    private var otherConsensusPeers: List<String> = allPeers.filter { it != peerAddress },
can you actually do that? to calculate other arg from another argument of the same function. Looks pretty sus to me (and not readable at all). Imo - better calculate it inside (in init or something)

2022-10-20 16:44 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/ratis/Constants.kt
> +        clusterGroupId = UUID(0, peersetId.toLong())
I don't think it'll work or at least it will destroy idea of two separate ratis instances. That's how ratis actually determines, if two peers are in the same group. Since we allow it, I think we are able to delete ratis.

2022-10-20 16:44 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/ratis/Constants.kt
> +        peers = ratisConfig.addresses[peersetIndex].mapIndexed { index, address ->
You did use it on k8s, right? Becuase I have a strange deja vu, since library we're using is unable to parse list of lists (which we exactly face here) from env variables, so it won't work on k8s. But maybe I'm wrong.

2022-10-20 16:44 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +    // TODO temporary, for backward compatibility
will this TODO be resolved in this PR?

2022-10-20 16:44 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/ApplicationMode.kt
> +    private val log = LoggerFactory.getLogger(DockerComposeApplicationMode::class.java)
It's nothing, but we're using `logger` everywhere, so for the sake of convention, please change it

2022-10-20 16:44 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/ApplicationMode.kt
> -    private fun getOtherPeers(config: Config, me: String): List<List<String>> =
Question: I don't see anywhere, where do you actually calculate `otherPeers` - don't we need them anymore?

2022-10-20 16:44 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/ApplicationMode.kt
> +private val log = LoggerFactory.getLogger(ApplicationMode::class.java)
Since you're creating logger here, couldn't you use it in `*ApplicationMode`?

2022-10-20 16:44 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/config.kt
> +    val peersetId: Int = -1,
+1 - I'm insecure about using -1 and empty strings (maybe PTSD from operative systems, but still) - IMO you could use nullables (I think it will even simplify these ifs in `Application.kt`)

2022-10-20 16:44 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +            "peerAddresses" to (1..numberOfPeersets).map { (1..numberOfPeersInPeersets[it - 1]).map { nonRunningPeer } }
I think those values up there (`ratisConfigOverrides`) have changed as well

2022-10-21 21:52 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/ApplicationMode.kt
> +    log.info("Using application mode $applicationModeString")
When you configure this app in a wrong way (e.g. by supplying wrong application mode), you will get a weird error message. So, until we change how the application is configured I would prefer currently to leave it at `info`.

2022-10-21 22:03 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/consensus/ratis/Constants.kt
>  ) {
Removed `Constants.kt`

2022-10-21 22:05 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +    // TODO temporary, for backward compatibility
It will be resolved in the next one

2022-10-21 22:06 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/consensus/ratis/Constants.kt
> +        clusterGroupId = UUID(0, peersetId.toLong())
How will it destroy the idea of two separate instances?

2022-10-21 23:11 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +    private val allPeers: List<String>,
Should have been a parameter

2022-10-21 23:36 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +    private val allPeers: List<String>,
Actually, I decided to make `otherConsensusPeers` a function

2022-10-21 23:37 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/utils/TestApplicationSet.kt
> +            "peerAddresses" to (1..numberOfPeersets).map { (1..numberOfPeersInPeersets[it - 1]).map { nonRunningPeer } }
Fixed as well

2022-10-21 23:39 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/ApplicationMode.kt
> -    private fun getOtherPeers(config: Config, me: String): List<List<String>> =
The idea of the simplification of the configuration is to configure peers instead of calculating them, k8s will require a major configuration overhaul

2022-10-22 00:20 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +    private var otherConsensusPeers: List<String> = allPeers.filter { it != peerAddress },
This fragment has been rewritten

2022-10-22 14:26 UTC, Davenury commented on .github/workflows/go.yml
> +        run: go build -o ucac
Delete it, I'm doing much more complex workflow now (including building command, setting up k8s and actually deploying and testing, if change is created)

2022-10-22 14:26 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/ratis/Constants.kt
> +        clusterGroupId = UUID(0, peersetId.toLong())
considering that ratis identifies groups by those uuids, I don't think something good will result from 2 groups having the same uuid, but Radek is much more an expert than me in ratis business

2022-10-22 18:25 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/consensus/ratis/Constants.kt
> +        clusterGroupId = UUID(0, peersetId.toLong())
If I understand everything correctly all nodes from the same peer set have to have the same clusterGroupId and this changes only that it will be generated based on peersetId instead of reading from config. So IMO it shouldn't break anything.

2022-10-22 18:25 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +    }
Why do we need this?

2022-10-22 18:49 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +    }
It allows to stop the server using an interrupt, which resulted from the fact that I removed `startBlocking` due to compatibility issues with `startNonblocking` (it was not calling `setPeerAddress`).

2022-10-22 18:50 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        assert(!otherConsensusPeers().contains(peerAddress))
removed

2022-10-22 19:12 UTC, Rados13 approved these changes

2022-10-22 19:14 UTC, Davenury approved these changes

2022-10-22 19:14 UTC, merged