Add sync and async API endpoints
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #47
Opened 2022-10-22 19:24 UTC by kjarosh

2022-10-23 18:21 UTC, Rados13 requested changes

2022-10-23 18:21 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +            cr.addRoutingFor(this)
What does this name mean?

2022-10-23 18:21 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/api/ApiV2Routing.kt
> +        return if (config.peerAddresses(config.peersetId).containsAll(peers)) {
Create a function like `allPeersFromSamePeerset` or move to variable or get peers from config peerset.

2022-10-23 18:21 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/common/ChangeResult.kt
> +data class ChangeResult(
Don't we need also state like `processed` for situations when change is still during processing?

2022-10-23 18:21 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetApiSpec.kt
> +            environment.getHost(1, 1) + ":" + environment.getMappedPort(1, 1)
Use string templates.
https://kotlinlang.org/docs/strings.html#string-templates

2022-10-23 18:21 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/gpac/MultiplePeersetSpec.kt
> +            applyCommittedPhaser.awaitAdvanceInterruptibly(applyCommittedPhaser.arrive(), 120, TimeUnit.SECONDS)
Why do we need to increase it that much?

2022-10-23 18:21 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +            (1..count).map { peerNetworkAlias(index + 1, it) + ":" + containerPort }
Use string templates.

2022-10-23 18:21 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +    }
```suggestion
    fun getHost(peersetId: Int, peerId: Int): String? = peers[PeerId(peersetId, peerId)]?.host
    
```

2022-10-23 18:21 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +    }
```suggestion
    fun getMappedPort(peersetId: Int, peerId: Int, port: Int = containerPort): Int? = peers[PeerId(peersetId, peerId)]?.getMappedPort(port)
    
```

2022-10-23 18:21 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestUtils.kt
> +    }
```suggestion
    fun getRepoRoot(): Path = Paths.get(".").absolute()
    
```

2022-10-23 18:21 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/utils/TestUtils.kt
> +    }
```suggestion
    fun getResource(name: String): Path = javaClass.classLoader.getResource(name)
    ?.resource.toURI().toPath()
    ?: throw AssertionError("Resource $name not found")
```

2022-10-23 18:52 UTC, Davenury requested changes
I think you forgot to add me to review, so I added myself. I have some questions and some requests of changes 😄

2022-10-23 18:52 UTC, Davenury commented on Dockerfile
> +ENTRYPOINT ["bash", "-c", "/application/PoC-*/bin/PoC"]
Why is that so? What was wrong with previous Dockerfile and what that change (and splitting it to two) introduces?

2022-10-23 18:52 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +            cr.addRoutingFor(this)
please, we're not golang programmers, use full names of variables for the readability sake. Also I think you don't use this variable anywhere else, so why don't you just 
```kotlin
ApiV2Routing(...).also { it.addRoutingFor(this) }
```?

2022-10-23 18:52 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/api/ApiV2Routing.kt
> +private const val DEFAULT_SYNC_TIMEOUT = "PT1M"
I think it should find it way in config file

2022-10-23 18:52 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/api/ApiV2Routing.kt
> +class ApiV2Routing(
I'm not master of JVM conventions, but I wouldn't encapsulate routing function in some class. I'd create routing function and pass something that solemn purpose would be deciding whether change should go through gpac or not (like historyManagement we've discussed on - the one that would gather all possible paths of change to go).

2022-10-23 18:52 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/api/ApiV2Routing.kt
> +    private val history: History = historyManagement.getState()
Do you use it anywhere?

2022-10-23 18:52 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/common/ChangeResult.kt
> +data class ChangeResult(
I agree, but I'd name it `ACCEPTED` OR `PROCESSING` since `processed` would be succes or failure

2022-10-23 18:52 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/api/ApiV2Routing.kt
> +    private suspend fun addChange(change: Change): CompletableFuture<ChangeResult> {
I think this should find it's place in earlier proposed class.

2022-10-23 18:52 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        TODO("Not yet implemented")
Will this TODO be resolved here? Since the other method is marked as deprecated...

2022-10-23 18:52 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetApiSpec.kt
> +        TODO("finish this test")
I hope this TODO will be resolved here, right?

2022-10-23 18:52 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +import org.testcontainers.lifecycle.Startable
I would like to remind you, why we didn't decide to use test containers:
1. It's hard to control protocol behavior without signals and you won't make them usable from Docker container.
2. Windows users (yes, I'm talking about myself and I'm proud of that) without proper configured Docker won't be able to use test containers.

2022-10-23 18:52 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +                    .withEnv("config_port", containerPort.toString())
I get that in test-containers we don't need to worry about two containers having the same port exposed?

2022-10-23 18:52 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +    fun getHost(peersetId: Int, peerId: Int): String? {
why don't you use `PeerId` class here?

2022-10-23 18:52 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetApiSpec.kt
> +}
I have to ask - how do you intend on testing async api on testcontainers without signals and delays / pooling?

2022-10-23 18:52 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetApiSpec.kt
> +            socketTimeoutMillis = 120000
Why so much time?

2022-10-23 18:52 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/gpac/domain/GPACProtocol.kt
> +    @Deprecated("use proposeChangeAsync")
Is it common to recommending using a method that isn't implemented yet?

2022-10-23 19:35 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +            cr.addRoutingFor(this)
A typo, fixed

2022-10-23 19:36 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/api/ApiV2Routing.kt
> +        return if (config.peerAddresses(config.peersetId).containsAll(peers)) {
Done

2022-10-23 19:37 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/common/ChangeResult.kt
> +data class ChangeResult(
`ChangeResult` models the resulting state, when a change is processing it does not have a `ChangeResult`

2022-10-23 19:40 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetApiSpec.kt
> +            environment.getHost(1, 1) + ":" + environment.getMappedPort(1, 1)
To be honest, string template would not solve the readability issue here, added method `getAddress`

2022-10-23 19:42 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/gpac/MultiplePeersetSpec.kt
> +            applyCommittedPhaser.awaitAdvanceInterruptibly(applyCommittedPhaser.arrive(), 120, TimeUnit.SECONDS)
The timeout generally needs to be a lot bigger than the expected operation time (possibly several orders of magnitude), so 120s would be better than 60s (because it's bigger and both are acceptable). I must have changed this timeout by accident so I reverted it.

2022-10-23 19:43 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +            (1..count).map { peerNetworkAlias(index + 1, it) + ":" + containerPort }
Done, however in my opinion it does not solve the readability issue

2022-10-23 19:43 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +    }
Done

2022-10-23 19:44 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +    }
Done

2022-10-23 19:44 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/utils/TestUtils.kt
> +    }
Done

2022-10-23 19:45 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/utils/TestUtils.kt
> +    }
Done

2022-10-23 19:53 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/Application.kt
> +            cr.addRoutingFor(this)
I can see your negative experience with golang. The name was a typo from the time the class was named CommonRouting, I've changed it to `.also`.

2022-10-23 19:54 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/api/ApiV2Routing.kt
> +private const val DEFAULT_SYNC_TIMEOUT = "PT1M"
Done

2022-10-23 19:59 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        TODO("Not yet implemented")
It will be resolved before we merge it to `main`. The deprecation is the final state, and this TODO is meant to be resolved in the target branch. In my opinion that's an acceptable situation.

2022-10-23 19:59 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetApiSpec.kt
> +        TODO("finish this test")
It will be resolved before merging to `main`

2022-10-23 20:10 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +import org.testcontainers.lifecycle.Startable
1. I'm well aware of that, the idea of these tests is not to control the internal state but rather test the application from the user's point of view. The second reason is to test Docker deployment — the application may work, but its container may not.
2. I think we can add an option to disable these tests, however IMO the fact that you do not have properly configured Docker on Windows is a questionable argument why we should not write tests

2022-10-23 20:15 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +                    .withEnv("config_port", containerPort.toString())
Generally in Docker, each container has its own IP, unless you use network_mode=host. So multiple containers may use the same port.

2022-10-23 20:16 UTC, mickel8 commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +import org.testcontainers.lifecycle.Startable
>  (yes, I'm talking about myself and I'm proud of that) 

Sir, pls uninstall this piece of shit :slightly_smiling_face:

2022-10-23 20:48 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +    fun getHost(peersetId: Int, peerId: Int): String? {
`PeerId` was meant to be a private class for the sole purpose of having a reasonable map key type

2022-10-23 21:01 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetApiSpec.kt
> +}
The same way a user would use the application — long polling in case of sync API and busy waiting / notifications in case of async API.

2022-10-23 21:10 UTC, kjarosh commented on src/test/kotlin/com/github/davenury/ucac/api/SinglePeersetApiSpec.kt
> +            socketTimeoutMillis = 120000
Sync API / long polling

2022-10-23 21:11 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/gpac/domain/GPACProtocol.kt
> +    @Deprecated("use proposeChangeAsync")
That's the final recommendation, however this PR does not merge these changes into `main` but into another development branch

2022-10-23 21:12 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/api/ApiV2Routing.kt
> +    private val history: History = historyManagement.getState()
Yes

2022-10-23 21:40 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/api/ApiV2Routing.kt
> +class ApiV2Routing(
I'm not sure about what JVM conventions you are talking about, but I tried to do something similar to a controller in Spring or a JAX-RS resource in Java EE.

I'm not sure what's the difference here between a function and a method — both solutions delegate routing initialization elsewhere, the function/method is only called in `Application` in order to add the routes imperatively. I used a class in order to simulate a resource due to the behaviors it has.

2022-10-24 10:37 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/api/ApiV2Routing.kt
> +    private val history: History = historyManagement.getState()
Won't it get deactualized? The name of the method stands that it is `getState` as in current state

2022-10-24 10:41 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/utils/ApplicationTestcontainersEnvironment.kt
> +import org.testcontainers.lifecycle.Startable
> > (yes, I'm talking about myself and I'm proud of that)
> 
> Sir, pls uninstall this piece of shit 🙂

Yo, language, we're all people of culture here 😉 Anyway, people will always complain one way or another so let me put this suggestion in the jar "when I'll have time to actually care for" 😃

2022-10-24 11:21 UTC, kjarosh commented on Dockerfile
> +ENTRYPOINT ["bash", "-c", "/application/PoC-*/bin/PoC"]
That's something to discuss: the original Dockerfile includes a building stage which increases building time (and therefore test execution time) by a lot, and additionaly it builds the application from scratch despite us having the application built locally. It creates a weird situation where the tests do not use the application built during gradle execution, and it creates a form of a cyclic dependency, because we use gradle to build the application within a Dockerfile which is used in tests during application building.

2022-10-24 16:52 UTC, Rados13 approved these changes

2022-10-24 17:15 UTC, Davenury approved these changes

2022-10-24 17:24 UTC, merged