Two different changes
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #64
Opened 2022-11-08 20:41 UTC by Davenury

2022-11-08 20:46 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/history/History.kt
> +        }
I'm not sure about the consequences it will bring. Swaping this entry will result in having different entry id, but since we're adding it only now, id of this entry could even be null, so we shouldn't have relied on it, right?

2022-11-08 20:47 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocol.kt
> +        val initVal = if (!shouldCheckForCompatibility(message.change.peers) || history.isEntryCompatible(message.change.toHistoryEntry())) Accept.COMMIT else Accept.ABORT
`My encoding is better than yours and to show my encoding is superior I will point out places I've changed in this file`
First one being here - I added `!shouldCheckForCompatibility`

2022-11-08 20:48 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocol.kt
> +                history.addEntry(message.change.toHistoryEntry(), !shouldCheckForCompatibility(message.change.peers))
here, I'm passing `!shouldCheckForCompability`

2022-11-08 20:48 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocol.kt
> +    }
I've also added this function

2022-11-08 22:08 UTC, Rados13 requested changes
I don't understand this PR, maybe because of a lack of context.

2022-11-08 22:08 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/history/History.kt
> +    fun addEntry(entry: HistoryEntry, swapParent: Boolean = false) {
Where do we use this function?

2022-11-08 22:30 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/history/History.kt
> +    fun addEntry(entry: HistoryEntry, swapParent: Boolean = false) {
This function is used in handleApply in GPAC for sure, I don't know where else (probably consensus uses it too), that's why I added default value.

2022-11-08 22:41 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocol.kt
> +    }
I'll answer here with the context of this PR: when we apply change now, we check if provided parentId is equal to the one that we expect (i.e. the ID of last change we did). All of our current tests (aside from this PR) execute only one change a top of the InitialHistoryChange which has the same ID in every peerset (since it's hash of {} string). Therefore no test has checked if our service works, if there are any other changes. So, for example:
Peerset1 has this state: I->ChangeA->ChangeB
And Peerset2 has this state:
I->ChangeC->ChangeD

Note that now, if we'd like to introduce change that should be present in both Peerset1 and Peerset2, we need to provide two parentIDs (which is final plan and according to Kamil we don't need that now). So, for now (and probably forever) we'll provide user request with only one parentID - the one of change from the peerset you're sending request to. Let's say (for example) that you (as user) send request for Peerset1, providing change with parentId = ChangeB.getId().
Now, when a leader from Peerset1 tries to execute this change, peers from Peerset2 checks their history and says that the change isn't compatible, as provided parentId isn't the one they expected (ChangeD.getId()), therefore they send initVal as ABORT. Leader sees that some of the peers sent ABORT, so he executes transaction to its end with according result (therefore not executing it at all). 
To prevent this behavior, I added a check if compability of changes should be checked - right now it's in trivial way - if change is executed in two peersets, changes shouldn't be validated. This allows peers from Peerset2 set their initVal to COMMIT.
The next change (one with swapping ids) is there to provide compability of parentIds - we use hashmap and iterate over ids, so we would have a break in chain of changes in Peerset2 if I didn't swap that id. As I wrote somewhere else, I don't know what exact consequences brings this swaping of id, but it's not any test-breaking behavior.

2022-11-12 08:49 UTC, kjarosh requested changes

2022-11-12 08:49 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/history/History.kt
> +    fun addEntry(entry: HistoryEntry, swapParent: Boolean = false) {
Instead of implementiclng hacks here, just call this function with different entry

2022-11-12 08:49 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocol.kt
> +        return peers.size == 1
This implementation requires a comment

2022-11-12 09:10 UTC, Rados13 submitted a review, later dismissed
Add comment required by Kamil and IMO PR is ready for merge.

2022-11-12 11:34 UTC, closed without merging