2PC
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #73
Opened 2022-11-23 22:50 UTC by Rados13

2022-11-24 16:42 UTC, Davenury requested changes

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/api/Worker.kt
> +enum class ProcessorJobType {
This is what I was talking about before and I think it could be somewhere 'higher'

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/AtomicCommitmentProtocol.kt
> +    fun getLogger(): Logger
I don't think implementation of atomic commitment should be used to get logger, nor should it be used to get peer resolver
Edit after seeing the rest of the code: If you create abstract class from it, you can pass peerResolver and logger to constructor of this class.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/AtomicCommitmentProtocol.kt
> +    fun putChangeToCompletableFutureMap(change: Change, completableFuture: CompletableFuture<ChangeResult>)
If this will be in all `AtomicCommitment` implementations, I'd change this interface to abstract class, have this map there and not create such method (since, I suppose, it will look the same across all implementations.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/AtomicCommitmentProtocol.kt
> +        GlobalScope.launch(MDCContext()) {
GlobalScope? I think we should create executor or use one we've created. This could easily destabilize tests, since Global Scope won't be affected by shutting down application.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/AtomicCommitmentProtocol.kt
> +        if (change.peers.isEmpty()) throw RuntimeException("Change without peers")
Since we're enriching the change with leader address, can something like that happen? If so, I'd use `IllegalStateException` but I guess it's just semantics, so you can ignore the exception change.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/AtomicCommitmentProtocol.kt
> +            return@map peerResolver.getPeersFromPeerset(peersetId!!) // TODO we need to specify peersetIds instead of peers
I think you can omit `return@map`

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/AtomicCommitmentProtocol.kt
> +            return@map peerResolver.getPeersFromPeerset(peersetId!!) // TODO we need to specify peersetIds instead of peers
Also this piece of code doesn't make much sense. If `peersetId` is null, executing `peersetId!!` will result in NullPointerException. You could get around that by executing something like this:
```kotlin
peerResolver.findPeersetWithPeer(peer)
    ?.let { peerResolver.getPeersFromPeerset(it) }
    ?: run { logger.error(...); throw SomeException() }
```
not sure about `run` though (but something like this should be ok)

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/AtomicCommitmentProtocol.kt
> +        }.map { peerset -> peerset.filter { it.globalPeerId != peerResolver.currentPeerAddress().globalPeerId } }
What does it do?

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +    override fun getPeerName() = "peerset${myPeersetId}/peer${myNodeId}"
Does this change between protocols? If not, I'd throw it to the interface / abstract class (whatever you'll decide)

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +
Too many enters (one is ok, two or more look weird 😄)

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        }
Maybe that's because I'm stupid with concurrency but why do you have to lock only this line? I mean the moment ThreadA get out of this line, ThreadB can get in and override `currentProcessedChange`, which will result in overriding it in ThreadA. Or maybe I'm wrong 😅

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +            "failed during processing acceptChange"
I'd mention that it's in 'TwoPC'

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +    }
I have a request - could you actally split it to multiple functions, each function representing a phase of 2PC? I think it would be more readable that way.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        if ((change is TwoPCChange).not()) {
I think more readable would be `change !is TwoPCChange`

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        }
I still think you aren't thread-safe.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +            throw TwoPCHandleException("TwoPCChange doesn't applied change")
`TwoPCChange didn't apply change` 😄

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +            askForDecisionChange(change)
I'd move the definition of the function right below this function.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +            throw TwoPCConflictException("We are blocked, because we didn't received decision change")
We will be blocked forever in that case. And, as I understand, after maxChangeRetries we decide it's enough and if leader wants to continue with the transaction, he has to do the effort? But as we don't have the CC mechanizm and leader doesn't recover the change if he fails... we'll be blocked forever?

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +                }
Did you include the test where we make change in both single peersets (different changes) and then introduce another change in both of there? This when is pretty complicated and the test I mentioned will make more of less sure that it works.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +            ?: throw ChangeDoesntExist(changeId)
This function doesn't 'handle' anything - it just returns change, therefore I'd change it's name.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        if (history.isEntryCompatible(change.toHistoryEntry()).not()) {
I don't feel the `.not()` at the end is more readable than `!` at the beginning. I feel like I ingest the whole expression and then there's "wait, it's actually negation of it all". But I guess it's a matter of taste.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        } else Unit
do you have to include something like that? since the function doesn't return anything, imo using `=` syntax is pointless.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        .let { consensusProtocol.proposeChangeAsync(change) }
`also` would be more syntactically correct, but `let` will also work.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPCProtocolClient.kt
> +        private val logger = LoggerFactory.getLogger(TwoPCProtocolClientImpl::class.java)
I think @kjarosh actually pointed out that it's better to use names, instead of classes. I don't know, so let him speak his mind.

2022-11-24 16:42 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPCProtocolClient.kt
> +                null
Why `Boolean?`, since you don't return `false` in here?

2022-11-24 16:42 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +            listOf(3, 3),
`changeAppliedPhaser` has 9 parties but you have 6 applications. How does it work XD?
Also, `electionPhaser` only has 5. Shouldn't we wait for all consensus peers to elect leader (if leader doesn't send this signal, ignore the second sentence).

2022-11-24 16:42 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +    @Disabled("Servers are not able to stop here")
Are they? Wasn't this problem with ratis?

2022-11-24 16:42 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +            executeChange("http://${peers[0][0]}/v2/change/sync?use_2pc", change(otherPeer))
I think you should add `use_2pc=true` but I may be wrong

2022-11-24 16:42 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +            var isChangeNotAccepted = true
Shouldn't it be `AtomicBoolean` since we will use it in SignalListener?

2022-11-24 16:42 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +    @Disabled("I am not sure if this is solid case in 2PC")
imo it should be replace with test `transaction should be processed after leader fails and then starts up and wants to get the transaction to an end`

2022-11-27 10:53 UTC, Rados13 commented on modules/common/src/main/kotlin/com/github/davenury/common/Change.kt
> +    abstract fun copyWithNewParentId(parentId: String): Change
Nope, I can't because copy method is only available for the data class.

2022-11-27 10:54 UTC, Rados13 commented on modules/common/src/main/kotlin/com/github/davenury/common/Change.kt
> +    }
I can't because the `Change` class doesn't have access to copy method, because it is not a data class.

2022-11-27 10:58 UTC, Rados13 commented on modules/common/src/main/kotlin/com/github/davenury/common/Change.kt
> +    val change: Change
Ok, it would imply that we will have to always pass named parameters for change and twoPCStatus or always explicitly pass null for `acceptNum`, but if you wish that. The customer is always right.

2022-11-27 11:04 UTC, Rados13 commented on modules/common/src/main/kotlin/com/github/davenury/common/exceptions.kt
> +class TwoPCHandleException(msg: String): Exception("In 2PC occurs error: $msg")
My idea was that TwoPCConflictException suggests that some change ends with conflict and TwoPCHandleException is a situation the client sends a bad request to 2PC.

2022-11-27 11:05 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/ApplicationUcac.kt
> +    private var twoPC: TwoPC? = null
I don't think that we need another layer of abstraction here as we can't handle the current ones.

2022-11-27 11:34 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/commitment/AtomicCommitmentProtocol.kt
> +        }.map { peerset -> peerset.filter { it.globalPeerId != peerResolver.currentPeerAddress().globalPeerId } }
Probably removing myself from the list of peers.

2022-11-27 11:41 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        }
Okay, you are right I should check first if any change is currently processed.

2022-11-27 11:51 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        if ((change is TwoPCChange).not()) {
Oh my god, I can't believe that someone decided to make something like `!is` instead of `is not`.

2022-11-27 11:52 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        }
We can talk about this on Monday.

2022-11-27 11:55 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +            throw TwoPCConflictException("We are blocked, because we didn't received decision change")
You know 2PC is blocking protocol so yes.

2022-11-27 11:59 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +                }
https://github.com/Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC/blob/c980c11de190fe3ffce10a4c514a631ffdf72779/src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt#L350-L463

Yes because I copy all tests from GPAC and tried to adjust them for 2PC.

2022-11-27 12:01 UTC, Davenury commented on modules/common/src/main/kotlin/com/github/davenury/common/Change.kt
> +    val change: Change
As I mentioned - if it will introduce complications, drop it 😂

2022-11-27 12:03 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        .let { consensusProtocol.proposeChangeAsync(change) }
We return `completableFuture` from this function, so how I can use `also` here?

2022-11-27 12:10 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/ApplicationUcac.kt
> +    private var twoPC: TwoPC? = null
I actaully meant the interface Kamil made - there's the one that already is implemented by `TwoPC` and `GPAC`. In this interface we could do:
```
companion object {
    fun createInstance(config: Config): AtomicCommitment {
        if (config.comitment == "2PC") return TwoPC(config)
        return GPAC(config)
    }
}```
or so. But it assumes that we won't use both 2PC and GPAC together and I don't know if this assumption is valid.

2022-11-27 12:12 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        if ((change is TwoPCChange).not()) {
XDDDDDD

2022-11-27 12:13 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        }
I don't know if I will be remembering it on Monday :smile: neither if I have any more valuable input than being a vibe check "hmm, this still doesn't look thread-safe for me" :smile:

2022-11-27 12:14 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +            listOf(3, 3),
It's pretty simple the signal `ConsensusLeaderElected` is called when a peer receives a message  `LeaderElected` which is only sent to followers. As we are waiting that both peersets to elect leaders and each peerset has got 3 peers, so one peer has to be a leader and the other two peers are followers. So to sum up 2 peersets multiplied by 2 followers in each peerset give us 4 signals on which we are waiting for.

2022-11-27 12:15 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +            throw TwoPCConflictException("We are blocked, because we didn't received decision change")
Yeah, of course I knew that :sweat_smile: I mean that it will be blocked forever in this case. shouldn't it ask forever? (so without the iteration condition?)

2022-11-27 12:16 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        .let { consensusProtocol.proposeChangeAsync(change) }
Ok, you can't :smile: I didn't notice we're returning it

2022-11-27 12:16 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +            listOf(3, 3),
As for `changeAppliedPhaser` it is similar because also only followers call that signal and each 2PC change consists of two consensus changes, so 2 multiplied by 4, gives us 8.

2022-11-27 12:17 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +    @Disabled("Servers are not able to stop here")
I am not sure but this test is disabled also in GPAC so I leave it as it is.

2022-11-27 12:18 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +            executeChange("http://${peers[0][0]}/v2/change/sync?use_2pc", change(otherPeer))
This test wasn't adjusted to 2PC as it is also disabled in GPAC.

2022-11-27 12:21 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/commitment/AtomicCommitmentProtocol.kt
> +    suspend fun proposeChangeAsync(change: Change): CompletableFuture<ChangeResult> {
After Dawid's suggestion, I converted the interface to an abstract class.

2022-11-27 12:29 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/api/Worker.kt
> +        enforceGpac: Boolean,
As always in this project.

2022-11-27 12:31 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/commitment/AtomicCommitmentProtocol.kt
> +    fun getPeersFromChange(change: Change): List<List<PeerAddress>> {
I moved all shared logic between 2PC and GPAC to AtomicCommitmentProtocol.

2022-11-27 12:40 UTC, Rados13 commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +    @Disabled("I am not sure if this is solid case in 2PC")
As each peer stores the state in memory, so leader's failure will lead to the loss of his whole state. So it can't retry a transaction, also it will be very difficult to finish the transaction for the second peer if the first peer will be stopped or will be recovering from failure. But we can talk about this on chat or tomorrow.

2022-11-28 20:13 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/api/ProcessorJob.kt
> +    }
As the companion object is empty for now, I'd get rid of it

2022-11-28 20:13 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        if (changeResult.status != ChangeResult.Status.SUCCESS) throw TwoPCConflictException("Change failed during committing locally")
But this shouldn't happen, right? Consensus will be blocked from outside and will infinitely repeat this change?

2022-11-28 20:13 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        }
Singal is something we use for tests. Why the inability to execute signal should  timeout change in production code?

2022-11-28 20:13 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocolAbstract.kt
> +    AbstractAtomicCommitmentProtocol(logger, peerResolver) {
@kjarosh do we really need this interface (I know perfectly well I was the one who introduced it but I wasn't sober back then) - imo we don't

2022-11-28 20:13 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocolAbstract.kt
> +class GPACProtocolImplAbstract(
`GPACProtocolImpl` will suffice imo.

2022-11-28 20:13 UTC, Davenury commented on src/main/kotlin/com/github/davenury/ucac/consensus/raft/infrastructure/RaftConsensusProtocolImpl.kt
> +        GlobalScope.launch(MDCContext()) {
usage of `GlobalScope` won't destabilize tests (even more)?

2022-11-28 20:13 UTC, Davenury commented on src/main/resources/application-integration.conf
> +
Isn't it needed in other conf files?

2022-11-28 20:13 UTC, Davenury commented on src/test/kotlin/com/github/davenury/ucac/api/TwoPCSpec.kt
> +            listOf(3, 3),
You said "pretty simple" but it's some high advanced math :smile:

2022-11-28 20:21 UTC, Rados13 commented on src/main/kotlin/com/github/davenury/ucac/commitment/TwoPC/TwoPC.kt
> +        }
Kamil suggested that we should change it in the future so I add TODOs.

2022-11-28 20:28 UTC, Rados13 commented on src/main/resources/application-integration.conf
> +
This param has got a default value and we only use it in 2PC tests so I don't see much benefit from adding it to other conf files, but as you requested that I will add this.

2022-11-29 00:20 UTC, kjarosh commented on src/main/kotlin/com/github/davenury/ucac/commitment/gpac/GPACProtocolAbstract.kt
> +    AbstractAtomicCommitmentProtocol(logger, peerResolver) {
You mean `SignalSubject`?

2022-11-30 18:54 UTC, Davenury approved these changes

2022-11-30 18:58 UTC, merged