Protocol - happy path + errors when cohorts aren't responding
Davenury/Unifying-Consensus-And-Atomic-Commitment-PoC pull request #9
Opened 2022-05-12 18:56 UTC by Davenury

no leader faults

2022-05-12 19:53 UTC, Rados13 requested changes

2022-05-12 19:53 UTC, Rados13 commented on build.gradle.kts
> +    implementation("io.ktor:ktor-jackson:$ktor_version")
Why did you change that, as a few lines lower, we import object mapper Jackson?

2022-05-12 19:53 UTC, Rados13 commented on src/main/kotlin/com/example/api/ProtocolRouting.kt
> +            val change = ChangeDto(call.receive())
I would make some convention and stay one way, `call.receive<ChangeDto>` or `ChangeDto(call.receive())`.

2022-05-12 19:53 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +}
I would move it GPACProtocol implementation or GPACProtocol interface as it shouldn't be used outside the context of GPAC and the name of this data class is very generic.

2022-05-12 19:53 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        this.state = this.state.copy(decision = true, acceptVal = Accept.COMMIT)
When we abort a transaction acceptVal wouldn't be `Accept.ABORT`?

2022-05-12 19:53 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        this.state = State.resetStateAfterTransaction(this.state)
Why do you reset state after a transaction?

2022-05-12 19:53 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        }
Is this httpClient blocking? I would use some async/await/future, because IMO it will be accurate to use this here.

2022-05-12 19:53 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +                    body = Agree(this@GPACProtocolImpl.state.ballotNumber, acceptVal, change)
For what purpose is this `@` here?

2022-05-14 16:28 UTC, Davenury commented on src/main/kotlin/com/example/api/ProtocolRouting.kt
> +            val change = ChangeDto(call.receive())
There's difference between those two. As `call.receive` is just a map, it was more natural to create `ChangeDto` with it as a parameter. As for the other way, it will try to serialize received map to this class - ChangeDto has `properties` map as its field, not the things we're sending.

2022-05-14 16:29 UTC, Davenury commented on build.gradle.kts
> +    implementation("io.ktor:ktor-jackson:$ktor_version")
It's more about ktor integration with jackson than jackson itself. Up to this PR we've used kotlinx serialization to serialize requests and it's not always perfect.

2022-05-14 16:30 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        this.state = this.state.copy(decision = true, acceptVal = Accept.COMMIT)
Ok I thought that apply means that we accept and commit this change - I'll change it

2022-05-14 16:31 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        this.state = State.resetStateAfterTransaction(this.state)
Originally, there's a line in article that each transaction has its own state. For now I just reset it, as I'm not convinced how can we keep track of the list of transactions without transaction id.

2022-05-14 16:33 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        }
It is blocking but I don't see, why async / await would be better?

2022-05-14 16:34 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +                    body = Agree(this@GPACProtocolImpl.state.ballotNumber, acceptVal, change)
TBH I'm not quite sure. I think about it like "`this` doesn't relate to the block of code you're in (the httpClient.post block in this case), but to the class you're in (GPACProtocolImpl in this case)".

2022-05-14 18:58 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        this.state = State.resetStateAfterTransaction(this.state)
Ok, I was thinking about the state as about transaction history. I would change this variable name maybe to pacState.

2022-05-14 19:03 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        }
For optimization reasons, e.g. when none of the peers will respond and you will wait for a timeout when it is blocking, you will be waiting `peers_number * timeout`, in async you will wait something closer to `timeout`.

2022-05-14 19:04 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +                    body = Agree(this@GPACProtocolImpl.state.ballotNumber, acceptVal, change)
Ok

2022-05-14 19:05 UTC, Rados13 commented on build.gradle.kts
> +    implementation("io.ktor:ktor-jackson:$ktor_version")
Ahh JVM and it's serialization libraries 😮‍💨

2022-05-14 19:13 UTC, Davenury commented on build.gradle.kts
> +    implementation("io.ktor:ktor-jackson:$ktor_version")
Ik if we wrote this in Haskel, there would be one (or not ans we would need to write it by ourselves) 😂

2022-05-21 18:19 UTC, Rados13 requested changes

2022-05-21 18:19 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        if (checkBallotNumber(message.ballotNumber)) {
I would check the negation of condition and throw the error earlier, it will remove one nesting.

2022-05-21 18:19 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +                ?: throw java.lang.IllegalStateException("Got apply for transaction that isn't in transactions map: ${message.ballotNumber}")
Are you sure that this should be that exception, as the earlier Exception is without `java.lang`?

2022-05-21 18:19 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        if (message.acceptVal == Accept.COMMIT) {
Parentheses are unnecessary

2022-05-21 18:19 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +            }
You can add if condition inside while, and on the end of the loop always do incrementation.

2022-05-21 18:19 UTC, Rados13 commented on src/test/kotlin/com/example/domain/GPACProtocolSpec.kt
> +        println(subject.getBallotNumber())
Do we still need this?

2022-05-22 07:50 UTC, Davenury commented on src/main/kotlin/com/example/Application.kt
> +    = peersAddresses.filterNot { it.contains("peer$nodeId") || it.contains("808$nodeId") }
Go BIG or go home 😄

2022-05-22 07:53 UTC, Davenury commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        if (message.acceptVal == Accept.COMMIT) {
I've heard that you should always add parentheses because in the future it'll be easier to add something inside if (also it's more readable). - And yeah, it was JVM senior, so I think he knows what he's talking about 😄

2022-05-22 07:54 UTC, Davenury commented on src/test/kotlin/com/example/domain/GPACProtocolSpec.kt
> +        println(subject.getBallotNumber())
Of course, without them nothing works 😄

2022-05-22 08:16 UTC, Rados13 commented on src/main/kotlin/com/example/domain/GPACProtocol.kt
> +        if (message.acceptVal == Accept.COMMIT) {
I don't think that paranthesses are more readable but, if you like it more this way ok, but according to kotlin coding convention paranthesses are required only for multiline statement.
https://kotlinlang.org/docs/coding-conventions.html#control-flow-statements

2022-05-22 08:53 UTC, Rados13 approved these changes

2022-05-22 08:53 UTC, merged